### ISSUE TITLE
Running python lld.py results in return to command prompt and nothing happens

### ISSUE THREAD

**Issue by Mr-Moto7** [mclmza/linkedin-learning-downloader#14]
This script worked flawlessly yesterday at the library.
I suspect that a captcha prompt during logon by the lld.py code is being encountered and causing the script  to exit.  Not sure how to get verbose status during execution.  Still trying to learn Python.
I am at the time of this comment accessing the linkedin website through my iphone hotspot which provides wifi to laptop workstation for the download.
Am I correct in my assumption or is there another issue here?  How do I circumvent the issue here?
Thankx for any help.Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Mr.Moto>cd\learning

C:\learning>python lld.py

C:\learning>python lld.py

C:\learning>

C:\learning>

![linkedin captcha check at login](https://user-images.githubusercontent.com/29337829/34083110-e16789aa-e338-11e7-9e52-433362e9dab1.jpg)

**Comment by mclmza** [comment]
You are correct. The only solution is to change your WiFi connection.

**Comment by Mr-Moto7** [comment]
Thank you Michele for your prompt reply!
