### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bgagan911** [mclmza/linkedin-learning-downloader#15]
The script ran perfectly twice. After that is started showing me the error:

```
Traceback (most recent call last):
  File "./lld.py", line 92, in <module>
    course_name = r.json()['elements'][0]['title']
KeyError: 'elements'
```

**Comment by mclmza** [comment]
Try to wait some time and run again the script.
Let me know if this works.

**Comment by bgagan911** [comment]
Nope. It doesn't work. Same error.

**Comment by mclmza** [comment]
Have you tried to change IP/machine?

**Comment by bgagan911** [comment]
Nope. does your script support proxy ? I will try doing that!
BTW what does the error tell? I'm new to python, is there a way I can debug this?

**Comment by a21-mohit** [comment]
you probably missed comma after course names in config file :) happened same to me

**Comment by bgagan911** [comment]
nope. can I proxy? any help on how to proxy ?
