### ISSUE TITLE
KeyError: 'elements'

### ISSUE THREAD

**Issue by ancgate** [mclmza/linkedin-learning-downloader#18]
Traceback (most recent call last):
  File "lld.py", line 92, in <module>
    course_name = r.json()['elements'][0]['title']
KeyError: 'elements'

**Comment by freedumb2000** [comment]
This is returned by r.json():
{u'status': 404}

**Comment by mclmza** [comment]
Can you specify what course are you trying to download?

**Comment by ancgate** [comment]
I got it work on my mac, but it looks like I was trying to download a course but use the wrong link. It is working now.

**Comment by lsaa2014** [comment]
@mclmza Hi,
I still have the same issue. I'm trying to download these 2:
Python 3 Essential Training, Python: Programming Efficiently

**Comment by surajasawa** [comment]
same issue

**Comment by mclmza** [comment]
Can you post your config.py (without username and password)

**Comment by surajasawa** [comment]
Sorted, the name was wrong
