### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character...

### ISSUE THREAD

**Issue by vincentSTO** [mclmza/linkedin-learning-downloader#19]
Issue: UnicodeEncodeError: 'ascii' codec can't encode character

Error message: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2713' in position 30: ordinal not in range(128).

Course: https://www.linkedin.com/learning/data-visualization-best-practices

Cause: Check mark character not supported by (https://codepoints.net/U+2713?lang=en)

Ouput Example:
```shell
[*] Parsing "Data Visualization  Best Practices" course's chapters
[*] [6 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Welcome"
[*] ------ Downloading video "What to expect in this course"
[*] ------ Downloading video "Using the exercise files"
[*] --- Parsing "1  Numbers Don't Lie  but Visualizations Do" chapters's videos
[*] --- [7 videos found]
[*] ------ Downloading video "Charts vs  graphs"
[*] ------ Downloading video "Organization matters"
[*] ------ Downloading video "Colors matter"
[*] ------ Downloading video "Complex vs  simple"
[*] ------ Downloading video "Keep scales consistent"
Traceback (most recent call last):
  File "lld.py", line 116, in <module>
    print '[*] ------ Downloading video "%s"' % video_name
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2713' in position 30: ordinal not in range(128)
```

config.py
```python
#!/usr/bin/python

USERNAME = 'Vincent@myemail.com'
PASSWORD = 'MyPassword'
COURSES = [

	'data-visualization-best-practices'
	
]

```

Fix drop all non ascii characters.
```python
line 105                 video_name = video_name.encode('ascii', 'ignore').decode('ascii')
```

**Comment by mclmza** [comment]
Looks like the name of the next video: '✓ Challenge: Find the data visualization mistakes', is causing the problem, probably for the symbol ✓.

**Comment by anas1996** [comment]
what is causing the problem it's python  can't handle special characters, not the operating system ,so you only need to comment the print() function as i did it works good for me,try to use this file and save it as .py  OK 
[lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1643907/lld.txt)

**Comment by mclmza** [comment]
I've changed the encoding to UTF-8, give it a try and let me know if it works now.
