### ISSUE TITLE
error  no such file or directory

### ISSUE THREAD

**Issue by nfsnfsnfs17** [mclmza/linkedin-learning-downloader#20]
Hi,

Trying to download 
COURSES = [ l-essentiel-de-gimp-2-6 ]
Begin to download and fail on IOerror 

[*] Obtained new session: AQEDASWXXXXXX anonymised XXXXXXXXXXXXXXXXXXXyOvBKoe
Fc79firFsnsmmSECeWUiFu-U5cauHU5APgau4Dsl3gHHRI1Zv4fSYG02DLZ2Um3jOAkX0ZKojt-UIFkU
Q0mVgzgHoi2pbXFdXz

[*] Parsing "L'essentiel de GIMP 2 6" course's chapters
[*] [20 chapters found]
[*] --- Parsing "Entrez dans GIMP et la retouche d'images" chapters's videos
[*] --- [0 videos found]
[*] --- Parsing "Exemples de retouche" chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "Créer un rendu esthétique"
[*] ------ Downloading video "Retoucher localement une photo"
[*] ------ Downloading video "Corriger des yeux rouges"
[*] ------ Downloading video "Remplacer un ciel par un autre"
[*] --- Parsing "Qu'est-ce que GIMP  " chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "Le nom GIMP"
Traceback (most recent call last):
  File "lld.py", line 118, in <module>
    (str(vc), video_name))
  File "lld.py", line 76, in download_file
    with open(file_path + '/' + file_name, 'wb') as f:
IOError: [Errno 2] No such file or directory: u"out/L'essentiel de GIMP 2 6/Qu'est-ce que GIMP  /1. Le nom GIMP.mp4"

Thanks a lot for this great job !

**Comment by mclmza** [comment]
Looks like the 'Qu'est-ce que GIMP' is generating the problem, I'll try to fix it as soon as possibile.

**Comment by nfsnfsnfs17** [comment]
Thanks a lot.

**Comment by stephenleo87** [comment]
Add a .strip() to the end of line# 98 in lld.py file and it should work.

chapter_name = re.sub(invalid_file_chars, " ", chapter['title']).strip()

**Comment by mclmza** [comment]
I've added ' char to the invalid chars, check if it works now.

**Comment by nfsnfsnfs17** [comment]
Hi,
The new one doesn't work.

I use @stephenleo87  edit, and it works.

Add a .strip() to the end of line# 98 in lld.py file and it should work.
chapter_name = re.sub(invalid_file_chars, " ", chapter['title']).strip()

Thank you very much for this very great job.

**Comment by stephenleo87** [comment]
@mclmza Pull request submitted :)
The problem was with some folders having a space at the end of the name causing issues on windows. strip() removes those trailing spaces.

**Comment by mclmza** [comment]
strip() function added.

**Comment by vintageDarkKNIGHT** [comment]
.strip() added but doesn't help
