### ISSUE TITLE
Cant download videos error  "cant encode character"

### ISSUE THREAD

**Issue by IzzyZ** [mclmza/linkedin-learning-downloader#23]
[*] Obtained new session: AQEDAQndWO4CSa4dAAABYS22zg4AAAFhUcNSDk0AQpBgLjFE3I0NJLo3QpYE8xYReadjWJKsjr6odWzj3gbgyAQEnE6hmkHgADHnc79U2Oq4hc4FARgwdnXxQljM5k_W_Y5B7nCmMIDzcOAH-YYrhMRi

[*] Parsing "Cómo presentar en público con eficacia" course's chapters
[*] [6 chapters found]
[*] --- Parsing "Introducción" chapters's videos
[*] --- [1 videos found]
Traceback (most recent call last):
  File "lld.py", line 117, in <module>
    print '[*] ------ Downloading video "%s"' % video_name
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u201c' in position 53: character maps to <undefined>

Thats the error i get when i put courses in Spanish:

COURSES = [
    'como-presentar-en-publico-con-eficacia'

Thanks for the help.,

**Comment by mclmza** [comment]
Are you sure to have pulled the latest version of the script? Just tried and worked for me.

**Comment by musito76** [comment]
Hello, same problem for me, it seems correlated to the ascii code or something similar. :(
_

> python linkedin UnicodeEncodeError: 'charmap' codec can't encode character u'\u2014'

_

**Comment by vinz313** [comment]
First and foremost, thank you so much mclmza for sharing this piece of code. It saved me countless hours!

I've had similar issues where some video names were containing other unicode chars (U+2713 aka checkmark). The program was crashing at `print '[*] ------ Downloading video "%s"' % video_name`.

I think it boils down to your recent pull request #16 where you moved from whitelisting common characters to blacklisting specific ones. I guess the motivation behind that change was to better handle different languages, but backlisting is generally a bad practice in my opinion.

I reverted the change to `invalid_file_chars = r'[^a-zA-Z0-9 \-\_]'` to be able to download the course 'data-visualization-best-practices' and I suggest you do the same as a temporary fix. Using the `unidecode` module might be an interesting option as well.

I'm not a guru of string encoding, but if you want to keep support for accented letters, other parts of the code would need to be updated, e.g. by using `.encode('UTF-8')` when needed.

Thanks again!

**Comment by IzzyZ** [comment]
Hi, sorry for the delay.

Well, yes i used the last version of the script and still no works:

w.e. 

[*] Obtained new session: AQEDAQndWO4FJ0bHAAABYT8TQZgAAAFhYx_FmE0AY_pVysAdp99TMrdG0jtGeXGZx4uJF6YvzO_LxO3vSl1wi1U2eGdog5LobxjPpPXA71FeWw_BxBhfy57UOktaUY5UVcsWrbOb2A9v52mV6ZLiyfhR

[*] Parsing "Desarrollo Android avanzado  Librerías" course's chapters
[*] [8 chapters found]
[*] --- Parsing "Introducción" chapters's videos
[*] --- [1 videos found]
Traceback (most recent call last):
  File "lld.py", line 117, in <module>
    print '[*] ------ Downloading video "%s"' % video_name
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u201c' in position 53: character maps to <undefined>

The link of the course is this:

https://www.linkedin.com/learning/desarrollo-android-avanzado-librerias

Thanks

**Comment by mclmza** [comment]
Wich OS are you using?

**Comment by mclmza** [comment]
I've added utf-8 encoding for the strings. Try now and let me know.

**Comment by IzzyZ** [comment]
Now works, thank you for your time 👍  💯
