### ISSUE TITLE
Invalid syntax and other issues

### ISSUE THREAD

**Issue by williamfgm96** [mclmza/linkedin-learning-downloader#25]
![capture-20180214-174418](https://user-images.githubusercontent.com/36491303/36232177-bc4af180-11ae-11e8-86eb-ca993972c55d.png)
As you can see there is a syntax problem in the lld.py file, after fix the issue another error shows up so It'd be great if you can fix it.

**Comment by HirenSJ** [comment]
@williamfgm96 Hey, can you post your python and pip version to check exact issue.

**Comment by johnhern2017** [comment]
except Exception, e:
        sys.exit('[!] Could not authenticate to linkedin. %s' % e)

**Comment by HirenSJ** [comment]
@johnhern2017 i have updated code and let's wait for author to approve it! thanks for update!

**Comment by williamfgm96** [comment]
@HirenSJ Sorry I don't know my pip version or if I've installed but my php version is 2.7.8

**Comment by mclmza** [comment]
@williamfgm96 the syntax is valid, looks like you are using Python 3.x

**Comment by williamfgm96** [comment]
Really?
I'm going to try again

**Comment by mclmza** [comment]
@williamfgm96  have tried it with Python 2.x?

**Comment by HirenSJ** [comment]
@williamfgm96 , hey please follow steps.
1) install python from below link
https://www.python.org/downloads/release/python-2714/
2) open command prompt and write word "python" and see if it's display version if not, follow below link steps (don't worry about windows version mentioned)
https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7
3) please follow instruction of this repository! it will works.

**Comment by williamfgm96** [comment]
@HirenSJ Thank you! It worked perfectly
