### ISSUE TITLE
No action "python lld.py"

### ISSUE THREAD

**Issue by cmXray** [mclmza/linkedin-learning-downloader#26]
When i run the "python lld.py" there is no action only returning. I attached screenshot
![ekran alintisi](https://user-images.githubusercontent.com/15652575/36448847-f7557e90-1699-11e8-856f-1a464a73c2a7.JPG)

**Comment by szymonk92** [comment]
Your password or login is invalid. Check your credentials.

**Comment by gatesnz** [comment]
Hi I am experiencing the same issue, i have checked the password and username is correct but still wont work

**Comment by gatesnz** [comment]
i stand corrected this is working now.
