### ISSUE TITLE
IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Patrikejane** [mclmza/linkedin-learning-downloader#27]
Got a issue as below 

```
[*] Parsing "Artificial Intelligence Foundations  Thinking Machines" course's chapters
[*] [8 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [1 videos found]
[*] ------ Downloading video "Welcome"
[*] --- Parsing "1  What Is Artificial Intelligence " chapters's videos
[*] --- [4 videos found]
[*] ------ Downloading video "The history of AI"
Traceback (most recent call last):
  File "lld.py", line 119, in <module>
    (str(vc), video_name))
  File "lld.py", line 77, in download_file
    with open(file_path + '/' + file_name, 'wb') as f:
IOError: [Errno 2] No such file or directory: u'out/Artificial Intelligence Foundations  Thinking Machines/1  What Is Artificial Intelligence/1. The history of AI.mp4'
```
But when I check the 'out/' directory I can see the 'out/Artificial Intelligence Foundations  Thinking Machines/1  What Is Artificial Intelligence/' created  any Idea why this is ?

**Comment by mclmza** [comment]
I've pushed a fix, let me know if it works now.

**Comment by Patrikejane** [comment]
@mclmza  Thank you, same fix I did and created a pull request. now it should be fine.  **I have a small question is there any possibility to getting the account banned or any other illegal situation according to the LinkedIn rules by making requests using this.**  This is just to clarify

**Comment by mclmza** [comment]
@Patrikejane I made the script for educational purpose. You can already download the videos with the dedicated Android and iOS apps, so I don't think you can get in any illegal situation, but maybe the script breaks the LinkedIn rules, so your account can be banned...
