### ISSUE TITLE
Download stops

### ISSUE THREAD

**Issue by salvodragotta** [mclmza/linkedin-learning-downloader#29]
Downloading just stops sometimes. I've tried this course: 'fusion-360-essential-training'. Once stopped at chapter 4. Another time at chapter 7. 
I'm running  lld.py with Python 2.7.13 Shell

**Comment by mclmza** [comment]
Do you receive any error messages?

**Comment by vintageDarkKNIGHT** [comment]
Yes, it says no such file or directory exists

**Comment by vintageDarkKNIGHT** [comment]
![issue1](https://user-images.githubusercontent.com/37188284/37563204-9da67568-2aa1-11e8-962b-cd4dd99d56b3.JPG)
This is the issue

**Comment by mclmza** [comment]
Have you got writing permissions?

**Comment by duracotton** [comment]
File path is too long I guess? Had this problem, too. Try putting the downloader to the top level of your drive, e.g. D:\

**Comment by mclmza** [comment]
No answers from the issue author.
