### ISSUE TITLE
Append a number to chapter

### ISSUE THREAD

**Issue by hervehobbes** [mclmza/linkedin-learning-downloader#3]
Please could you append a number to each chapter, like for videos?
It will help to see the videos in the right order.

**Comment by mclmza** [comment]
I'll do as soon as possible!

**Comment by hervehobbes** [comment]
Thank you very much.

**Comment by anas1996** [comment]
[lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1533333/lld.txt)

**Comment by williamfgm96** [comment]
It didn't work
