### ISSUE TITLE
print '[*] Obtained new session: %s' % session

### ISSUE THREAD

**Issue by Mageshwaran2314** [mclmza/linkedin-learning-downloader#30]
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->-r requirements.txt (line 1))

E:\do\linkedin-learning-downloader-master>python lld.py
  File "lld.py", line 50
    print '[*] Obtained new session: %s' % session
                                       ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by mclmza** [comment]
@Mageshwaran2314 which python version are you using?

**Comment by Mageshwaran2314** [comment]
@mclmza  python 3.6.1
when I try to run it in python 2, by default it takes python3

**Comment by mclmza** [comment]
The script is written in Python 2.7, doesn't work with Python 3.x interpreter.

**Comment by Mageshwaran2314** [comment]
Thanks @mclmza
