### ISSUE TITLE
KeyError Traceback

### ISSUE THREAD

**Issue by vintageDarkKNIGHT** [mclmza/linkedin-learning-downloader#34]
I find this issue when downloading.
---------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
   File "lld.py", line 93, in <module>
      course_name = r.json()['elements'][0]['title']
KeyError: 'elements'
---------------------------------------------------------------------------------------------------------

**Comment by abc9987** [comment]
Same here..

**Comment by afahru** [comment]
Hi,

It's work for me, here's a step:

Edit file `config.py` and change your BASE_DOWNLOAD_PATH, in this case i tried to download more than one course to one folder but sometimes doesn't work, so i change the path from 'E:/Downloads/Caurse' to 'E:/Downloads/Caurse2'.

#Example 1#
USERNAME = 'user@email.com'
PASSWORD = 'password'
BASE_DOWNLOAD_PATH = 'E:/Downloads/Caurse' #use "/" as separators

COURSES = [
    'it-security-foundations-core-concepts'
]

#Example 2#
USERNAME = 'user@email.com'
PASSWORD = 'password'
BASE_DOWNLOAD_PATH = 'E:/Downloads/Caurse2' #use "/" as separators

COURSES = [
    'javascript-for-web-designers-2'
]

**Comment by mclmza** [comment]
No answers from the issue author.
