### ISSUE TITLE
Add incrementing numbers for chapters

### ISSUE THREAD

**Issue by williamfgm96** [mclmza/linkedin-learning-downloader#38]
I was to download the course `visual-c-plus-plus-esencial` but even the videos are in order the chapters don't.
![schot1](https://user-images.githubusercontent.com/36491303/37568999-9210ac10-2aaa-11e8-8554-43a033c109e6.jpg)
![schot2](https://user-images.githubusercontent.com/36491303/37569000-9527e9d6-2aaa-11e8-95b3-70d0c718228d.jpg)
So please add that function and about the numbers some platforms don't recognize very well a number list of one digit. e.g. 1,10,11,12...,2,20,21,22 etc.
So if you can add a zero to make them of two digits. I hope you understand me.

**Comment by williamfgm96** [comment]
I've resolved the problem but I don't know how to add it.

The code:
![capture-20180318-142629](https://user-images.githubusercontent.com/36491303/37570032-7fe60bc6-2ab8-11e8-97f7-d9d1428baa66.png)

The result:
![capture-20180318-142701](https://user-images.githubusercontent.com/36491303/37570040-92a889be-2ab8-11e8-9440-69e980e71734.png)

**Comment by duracotton** [comment]
Try my version here: https://github.com/mclmza/linkedin-learning-downloader/issues/40

**Comment by williamfgm96** [comment]
Resolved
[lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1824000/lld.txt)
