### ISSUE TITLE
Various additions: subtitle & exercise downloads, file numbering, etc.

### ISSUE THREAD

**Issue by duracotton** [mclmza/linkedin-learning-downloader#40]
Hi all,

see my pull request for all changes: https://github.com/mclmza/linkedin-learning-downloader/pull/39

**Comment by williamfgm96** [comment]
I made some changes, but finally I resolved all the issues.
Check it out: [lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1823990/lld.txt)

**Comment by mclmza** [comment]
@duracotton @williamfgm96 give me some time to check the edits and I'll merge the new features.

**Comment by duracotton** [comment]
@mclmza Just updated it again, just see my pull request. I'm not a programming pro and the code is a bit messy, but it works.

**Comment by williamfgm96** [comment]
@duracotton Your code is great but has some problems. I made some changes to your code and now it works for me.

**Comment by duracotton** [comment]
@williamfgm96 I'm interested in that, can you provide more info what problems exactly occured and which lines you changed? Was it only the encoding (UTF-8 -> cp1252)?

**Comment by williamfgm96** [comment]
@duracotton Sure.
1. The encoding `utf-8` doesn't work with Spanish characters, I tested it. But `cp1252` works perfectly.
2. The `invalid_file_chars = r'[^A-Za-z0-9\-\.]+'` cause that in some title courses/chapters/files doesn't appear so I recommend just use this `invalid_file_chars = r'[\\/*¿?:,"\'<>|]'` so far any problem with that.
3. The lines 
`umap = {ord(key):unicode(val) for key, val in replacementDictionary.items()}
string = string.translate(umap)`
makes me some problems, so I make it a comment but that is my case.
4. I added `.zfill(2)` to `chapter_index` and `video_index` to make one digit numbers "1-9" into two digit numbers "01-09".
5. And I change the ` - ` in `file_path = 'C:/Cursos/%s (%s)/%s. %s' % (course_name,course_releasedate,str(chapter_index).zfill(2),chapter_name)
                    file_name = '%s. %s' % (str(video_index).zfill(2), video_name)` for the dot.

**Comment by duracotton** [comment]
Thanks! Looks like most of them are adaption needed for your localization and/or wasn't compatible with yours ;-)
zfill(2) is a good idea, I adopted that.
For the replacement of the "-" by dot: That would result in a subfolder naming e.g. "03. 2. Cloud Best Practices". Personally I find the "-" more separating in this case: "03 - 2. Cloud Best Practices". But that's just a personal taste.

My account is still blocked by LinkedIn. Will try again tomorrow. Guess I tested too much.

**Comment by williamfgm96** [comment]
Ok man no problem. Thanks for consider my contribution! ^-^

**Comment by mclmza** [comment]
@duracotton @williamfgm96 I'm very busy at the moment, I'll do some test as soon as possible and accept your push requestes, sorry for the wait...

**Comment by larslemos** [comment]
@mclmza This PR works good.
Its a good contribution, any plan to close soon?

**Comment by mclmza** [comment]
Yeah, this week I'll try to find some time to test and accept it.

**Comment by mclmza** [comment]
Merge accepted, a big thanks to @duracotton and @williamfgm96 for the great work.
