### ISSUE TITLE
Code is not working.

### ISSUE THREAD

**Issue by candyalladi** [mclmza/linkedin-learning-downloader#43]
Code is not working. Error at "import statements" i.e. unable to import all modules/libs. error is below

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2242a6eaf4d0> in <module>()
----> 1 import cookielib
      2 import os
      3 import urllib
      4 import urllib2
      5 import sys

ModuleNotFoundError: No module named 'cookielib'.

Please provide working code. I am running above code on Anaconda3

**Comment by mclmza** [comment]
The script is wrote in Python 2.7

**Comment by candyalladi** [comment]
I could able to convert code to Python 3.6. However I have issue with downloading videos. Only sample videos are downloaded, while downloading other videos it gives me 

" Can't download the video "...........", probably is only for premium users".

If you can provide a code to download all videos irrespective of premium or non premium, that would be really g8.

**Comment by williamfgm96** [comment]
@candyalladi You need to be premium to download videos, the code was wrote with that purpose.

**Comment by candyalladi** [comment]
premium account for Linkedid??. In that case, I did not get the intended usage of code.

**Comment by duracotton** [comment]
How else should the downloader be able to access a whole learning course? It's not bypassing the accessibility by using a security hole or similar..
