### ISSUE TITLE
error "Your IP may have been temporarily blocked"

### ISSUE THREAD

**Issue by rammurti84** [mclmza/linkedin-learning-downloader#47]
C:\DATA\Docs\Util\linkedin-learning-downloader-master>python lld.py
[Fatal] Your IP may have been temporarily blocked
[Notice] Exception hit

**Comment by candyalladi** [comment]
try to include below lines of code 

import urllib 
import urllib.request as urllib2

in-case if you find any module related error. install those modules using pip install command

**Comment by mclmza** [comment]
No answers from the issue author.
