### ISSUE TITLE
Problems with languages ​​other than English

### ISSUE THREAD

**Issue by phibbe** [mclmza/linkedin-learning-downloader#49]
You can reproduce this if you set the profile language in the settings of your account to German

![language](https://user-images.githubusercontent.com/38150953/38451904-4ebd2384-3a28-11e8-88cb-88ebab96f5a2.png)

ps: a thousand thanks very useful tool !!!

**Comment by duracotton** [comment]
I am German and my own pull-request is working, maybe try that version?
