### ISSUE TITLE
Ignore already existing files

### ISSUE THREAD

**Issue by waheed1987** [mclmza/linkedin-learning-downloader#50]
Can someone please modify the code so that the file is not get's downloaded if it already exists on location?

**Comment by williamfgm96** [comment]
That change already exist

**Comment by waheed1987** [comment]
Where can I download that? because I am running the latest code and that is downloading all the videos again.

**Comment by williamfgm96** [comment]
https://github.com/duracotton/linkedin-learning-downloader
This fork has the newest changes check it out

**Comment by waheed1987** [comment]
Having this error, http://prntscr.com/j2568i

**Comment by waheed1987** [comment]
Sorry,
I replaced only program file,
Now replacing the config file as well.

**Comment by williamfgm96** [comment]
Yes, download all the files

**Comment by waheed1987** [comment]
It started downloading again, It seems names are different. I think this is good and will work best in future, Thank you very much friend.

**Comment by williamfgm96** [comment]
@duracotton I have a problem with the program, I can't download anything
I opened an issue but I got anything to resolve it
Help me

**Comment by mclmza** [comment]
Merged the pull, now the newest features are implemented.
