### ISSUE TITLE
Running Python

### ISSUE THREAD

**Issue by pheemmmy** [mclmza/linkedin-learning-downloader#51]
I am new to programming. To run those commands. I downloaded python 2.70. 
I run the command line. I was unable to get started. I do not know how to install the requirements?. 

Kindly help please

**Comment by duracotton** [comment]
If you installed Python correctly, just open the cmd and the command "pip" should start the python package manager. Then you're good to go and just need to run the command " pip install -r requirements.txt" (can be found in the description here on github) in the path of the requirements.txt

You can start the tool by using the cmd too: python lld.py

**Comment by williamfgm96** [comment]
@duracotton I've got this error
![capture-20180414-100704](https://user-images.githubusercontent.com/36491303/38769630-af8867b6-3fcb-11e8-9b4a-c96abfffcca7.jpg)

**Comment by pheemmmy** [comment]
Thank you so much, It worked. 
I couldn't execute the script: python lld.py

PS C:\linkedin\linkedin-learning-downloader-master> python lld.py
python :   File "lld.py", line 106
At line:1 char:1
+ python lld.py
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  File "lld.py", line 106:String) [], Remote 
   Exception
    + FullyQualifiedErrorId : NativeCommandError
 
    print 'Error. Deleting last incomplete file. Also check last created file manually 
for integrity'
                                                                                          
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Error. Deleting 
last incomplete file. Also check last created file manually for integrity')?

**Comment by pheemmmy** [comment]
Is the script still working?. 
I have tried with different version of python.
