### ISSUE TITLE
API doesn't work anymore 

### ISSUE THREAD

**Issue by abedoz** [mclmza/linkedin-learning-downloader#52]
For the last three days I'm trying to download from L.I. Lynda to no luck.
below is what i keep getting:

> Traceback (most recent call last):
>   File "lld.py", line 269, in <module>
>     bookmarked_courses = parse_bookmarks()
>   File "lld.py", line 186, in parse_bookmarks
>     course_slug = course['content']['com.linkedin.learning.api.ListedCourse']['slug']
> KeyError: 'com.linkedin.learning.api.ListedCourse'

**Comment by williamfgm96** [comment]
Try this 
[lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1945736/lld.txt)

**Comment by abedoz** [comment]
Unfortunately, Same :(

> Traceback (most recent call last):
>   File "lld.py", line 220, in <module>
>     bookmarked_courses = parse_bookmarks()
>   File "lld.py", line 183, in parse_bookmarks
>     course_slug = course['content']['com.linkedin.learning.api.ListedCourse']['slug']
> KeyError: 'com.linkedin.learning.api.ListedCourse'

**Comment by williamfgm96** [comment]
So try a version without the parse bookmarked
[lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1945827/lld.txt)
 I hope that help, if not let us know

**Comment by abedoz** [comment]
Worked like a charm!
Thanks million.

**Comment by williamfgm96** [comment]
Sorry but that's all we can get so far
