### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(cookie_jar._cookies)?

### ISSUE THREAD

**Issue by TravelingMan32** [mclmza/linkedin-learning-downloader#53]
Hello All,
I am completely newbie to all of this, so this may very well be user error.
Below is the error message I get after attempting to initiate the downloads:

PS C:\Users\-------\Desktop\linkedin-learning-downloader-master> python lld.py
  File "lld.py", line 40
    print cookie_jar._cookies
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(cookie_jar._cookies)?

I've input the correct user and pass, and pasted the end of the url for the course into the config file, saved it, and closed it before initiating the download.

Thank you for any and all clarification.

**Comment by TravelingMan32** [comment]
After reading that Python 27 is required, I downloaded and installed it. Python 37 remains installed on the OS (win7). Could 37 be creating a conflict? Do I need to uninstall 37 in order for this the downloader to work?

**Comment by TravelingMan32** [comment]
Initially, I had installed Python 37, and after reading that Python 27 is required for this software, I downloaded and installed it, and attempted to use the downloader. Could the presence of 37 on the OS (win7) be conflicting? Should I uninstall 37? Thank you for your feedback.

**Comment by RamiBarghouthi** [comment]
Same thing happened with me and I uninstalled the 3.xx version and installed the 2.7 version and it worked.

**Comment by TarekMan** [comment]
same problem with version 2.x and 3.x (win7), 
but the first time the code works well, after I repeated the method it does not,

**Comment by TravelingMan32** [comment]
Thank you for the reply. I've uninstalled 37, and installed the latest version of 27, but have encountered a new error which I will be describing in another thread already opened.
