### ISSUE TITLE
cant work in 2.7

### ISSUE THREAD

**Issue by byfsdhr** [mclmza/linkedin-learning-downloader#55]
[*] Obtained new session: AQEDARu9TOQCaXALAAABYyP-EvQAAAFjSAqW9FEAtJozm1P2YVAZijNOJjrFHrbWyxJSZELNnLw7VlspBHHwH-3-E2RBn7uveWgjGw-r_iUimDjybMs46YOSvgUBHoC-hTop6R2jg1z4oWYCeLY9BLtk
[*] Total number of online bookmarked courses: 10
Traceback (most recent call last):
  File ".\lld.py", line 269, in <module>
    bookmarked_courses = parse_bookmarks()
  File ".\lld.py", line 186, in parse_bookmarks
    course_slug = course['content']['com.linkedin.learning.api.ListedCourse']['slug']
KeyError: 'com.linkedin.learning.api.ListedCourse'

**Comment by TravelingMan32** [comment]
Using the latest version of 27, this is the error message I get, which appears to be identical to the error byfsdhr is getting as well:

{'.linkedin.com': {'/': {'lang': Cookie(version=0, name='lang', value='"v=2&lang
=en-us"', port=None, port_specified=False, domain='.linkedin.com', domain_specif
ied=True, domain_initial_dot=False, path='/', path_specified=True, secure=False,
 expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=Tr
ue), 'bcookie': Cookie(version=0, name='bcookie', value='"v=2&2e55aebc-b4c3-41a7
-85d6-440f96fb1e68"', port=None, port_specified=False, domain='.linkedin.com', d
omain_specified=True, domain_initial_dot=True, path='/', path_specified=True, se
cure=False, expires=1588672726, discard=False, comment=None, comment_url=None, r
est={}, rfc2109=False), 'liap': Cookie(version=0, name='liap', value='true', por
t=None, port_specified=False, domain='.linkedin.com', domain_specified=True, dom
ain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1533
334875, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False),
'lidc': Cookie(version=0, name='lidc', value='"b=VB72:g=1385:u=3:i=1525558876:t=
1525635445:s=AQGFua2oasm3zc3zeDq8_Ux3KeBUkUKz"', port=None, port_specified=False
, domain='.linkedin.com', domain_specified=True, domain_initial_dot=True, path='
/', path_specified=True, secure=False, expires=1525635445, discard=False, commen
t=None, comment_url=None, rest={}, rfc2109=False)}}, '.www.linkedin.com': {'/':
{'li_at': Cookie(version=0, name='li_at', value='AQEDASboNMgDQdoSAAABYzJlFvwAAAF
jVnGa_E4AWSR_6V6UOF7R6WDolkA8Nc1jQ56jgpLebk1EzhGGu21FJ1APvcNC5o-HMxfR789StXqsOsL
hD0Yea1XQ-ZdqBft1SBpaZK8qVOBO9ehRcv3lUheO', port=None, port_specified=False, dom
ain='.www.linkedin.com', domain_specified=True, domain_initial_dot=True, path='/
', path_specified=True, secure=True, expires=1557094875, discard=False, comment=
None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False), 'bscookie': Coo
kie(version=0, name='bscookie', value='"v=1&201805052221144a4eba1f-ecc0-438a-8b3
4-b02b1677c816AQHE33gjv-pZsV4NXbSsqSe8kt8uXgYB"', port=None, port_specified=Fals
e, domain='.www.linkedin.com', domain_specified=True, domain_initial_dot=True, p
ath='/', path_specified=True, secure=True, expires=1588672726, discard=False, co
mment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False), 'sl': Coo
kie(version=0, name='sl', value='"v=1&whQcx"', port=None, port_specified=False,
domain='.www.linkedin.com', domain_specified=True, domain_initial_dot=True, path
='/', path_specified=True, secure=False, expires=1533334861, discard=False, comm
ent=None, comment_url=None, rest={}, rfc2109=True), 'JSESSIONID': Cookie(version
=0, name='JSESSIONID', value='"ajax:3813228505076037961"', port=None, port_speci
fied=False, domain='.www.linkedin.com', domain_specified=True, domain_initial_do
t=True, path='/', path_specified=True, secure=True, expires=1533334861, discard=
False, comment=None, comment_url=None, rest={}, rfc2109=True)}}, 'www.linkedin.c
om': {'/': {'visit': Cookie(version=0, name='visit', value='"v=1&G"', port=None,
 port_specified=False, domain='www.linkedin.com', domain_specified=False, domain
_initial_dot=False, path='/', path_specified=True, secure=False, expires=1588630
861, discard=False, comment=None, comment_url=None, rest={}, rfc2109=True), 'leo
_auth_token': Cookie(version=0, name='leo_auth_token', value='"GST:UDDAXQHnxD7Wp
WSv3oufqLtaM7cOLDCBUPufuOpFoHEXd2nwSWKveu:1525558875:805190557bb1c771f7d9b01e8f4
4f651175cabc7"', port=None, port_specified=False, domain='www.linkedin.com', dom
ain_specified=False, domain_initial_dot=False, path='/', path_specified=True, se
cure=False, expires=1525560660, discard=False, comment=None, comment_url=None, r
est={}, rfc2109=True)}}}
[*] Obtained new session: AQEDASboNMgDQdoSAAABYzJlFvwAAAFjVnGa_E4AWSR_6V6UOF7R6W
DolkA8Nc1jQ56jgpLebk1EzhGGu21FJ1APvcNC5o-HMxfR789StXqsOsLhD0Yea1XQ-ZdqBft1SBpaZK
8qVOBO9ehRcv3lUheO
[*] Total number of online bookmarked courses: 425
Traceback (most recent call last):
  File "lld.py", line 269, in <module>
    bookmarked_courses = parse_bookmarks()
  File "lld.py", line 186, in parse_bookmarks
    course_slug = course['content']['com.linkedin.learning.api.ListedCourse']['s
lug']

Being completely new to Python and such, I am left puzzled as to what to do.

Thank you for any feedback or solutions.

**Comment by williamfgm96** [comment]
Looks like LinkedIn got down the bookmark api I guess, anyway I recommend you to use this code
[lld.txt](https://github.com/mclmza/linkedin-learning-downloader/files/1977415/lld.txt)
Let me know if still work

**Comment by TravelingMan32** [comment]
It seems like they are ahead of every step these days. =P Tried the code and this is what I got:

C:\linkedin-learning-downloader-master>python lld.txt
python: can't open file 'lld.txt': [Errno 2] No such file or directory

**Comment by williamfgm96** [comment]
@TravelingMan32 You have to replace the ".txt" extension by ".py"

**Comment by TravelingMan32** [comment]
@williamfgm96 To clarify, by saying replace the ".txt" extension by ".py", are suggesting to renaming the file "lld.py"  to "lld.txt" ?

**Comment by williamfgm96** [comment]
Viceversa, and yes.

**Comment by TravelingMan32** [comment]
@williamfgm96 How do I go about doing that? Using win7 64bit, and renaming the file didn't change it's file association. Would I do this using notepad ++? Or something else?

**Comment by williamfgm96** [comment]
@TravelingMan32 That doesn't matter, just change the file extension for ".py" and try to download.

**Comment by mclmza** [comment]
Have you tried the new version?
