### ISSUE TITLE
Move basic course info to separate text file, remove date from course folder name.

### ISSUE THREAD

**Issue by DanielDut** [mclmza/linkedin-learning-downloader#58]
- Move basic information about each course like _course name, release date, course link, etc._ into a text file (maybe _README.txt_?).
- Remove release date from course folder name.

**Comment by DanielDut** [comment]
I can take this on. Already done on my local machine but don't have permission to push to this repo.

**Comment by mclmza** [comment]
I've refactored the code and implemented the features.
