### ISSUE TITLE
keyError !!!

### ISSUE THREAD

**Issue by TarekMan** [mclmza/linkedin-learning-downloader#61]
![001](https://user-images.githubusercontent.com/38918604/40230982-b4d23114-5a99-11e8-82dc-94cc52ce60d1.jpg)

**Comment by juandeargentina** [comment]
same error here!. 
any news?

**Comment by mclmza** [comment]
I’m refactoring the code and fixing the issue.

**Comment by mclmza** [comment]
Code refactored.
