### ISSUE TITLE
Subtitles shown all at once in VLC

### ISSUE THREAD

**Issue by sojusnik** [mclmza/linkedin-learning-downloader#62]
When viewing a video course with enabled subtitles, then those are shown all at once in the first seconds of a video, to completely disappear afterwards.

Happens with VLC 2.2.6 on Ubuntu 17.10.

Can somebody confirm this?

**Comment by Ryan147** [comment]
Yes there is an issues with the subtitles. 

I have the same experience as yours. They are shown right from the start and then they are gone.

**Comment by Ryan147** [comment]
Format of a non working subtitle captured by the script:

1
0:00:00.070 --> 0:00:02.040
- Hi, I'm Brad Batesole,

2
0:00:02.040 --> 0:00:04.090
and welcome to Growth Hacking Fundamentals.

==================

Format of a working subtitle:

1
00:00:01,00 --> 00:00:02,07
- Do you ever wonder what drives

2
00:00:02,07 --> 00:00:04,08

**Comment by sojusnik** [comment]
Are your subtitles shown properly, if you change their format to the one
above? I changed mine, but it didn't help.

Ryan147 <notifications@github.com> schrieb am Fr., 25. Mai 2018 um
17:21 Uhr:

**Comment by mclmza** [comment]
Code refactored and issue fixed.
