### ISSUE TITLE
Error parse_bookmarks

### ISSUE THREAD

**Issue by gostrafx** [mclmza/linkedin-learning-downloader#64]
![capture](https://user-images.githubusercontent.com/13601626/40526410-a4caa90c-5fe6-11e8-8373-71fe0f72cab4.PNG)

line 182, in parse_bookmarks
    with open("config.py", "r") as config_file: #copy everything from old config to memory for easier inserting new lines in center of file
IOError: [Errno 2] No such file or directory: 'config.py'

**Comment by mclmza** [comment]
I’m refactoring the code and fixing the issue.

**Comment by mclmza** [comment]
Code refactored.

**Comment by duracotton** [comment]
Hi @mclmza ,
did you remove my bookmark parsing feature I introduced with some pull request some time ago? :)
Did it cause any problems?

**Comment by mclmza** [comment]
Check #67, #64, #61, #52
