### ISSUE TITLE
2019 courses issues

### ISSUE THREAD

**Issue by jAckercod3** [mclmza/linkedin-learning-downloader#66]
First of all thank you for this wonderful script.  However, i am facing a problem in a 2019 course.

Please find below the  error output from script.

>[*] Total number of online bookmarked courses: 1

[*] __________ Starting download of course "AutoCAD 2019 Essential Training" __________
[*] Access to full course is GRANTED :). Start downloading.

[*] Course description: downloading...
[*] --- finished.

[*] Exercise file (3 MB): downloading...
[*] --- finished.

[*] Parsing course's chapters
[*] [22 chapters found]

[*] --- Parsing chapter #01 "" for videos
[*] --- [4 videos found]
||       New folder not found. Checking for old folder
D:/Lynda/AutoCAD 2019 Essential Training (2018.03)\Description.txt
D:/Lynda/AutoCAD 2019 Essential Training (2018.03)/01 -
D:/Lynda/AutoCAD 2019 Essential Training (2018.03)\01 -
         Old type chapter folder FOUND - Rename successful
D:/Lynda/AutoCAD 2019 Essential Training (2018.03)\Ex_Files_AutoCAD_2019_EssT.zip
D:/Lynda/AutoCAD 2019 Essential Training (2018.03)/01 -
D:/Lynda/AutoCAD 2019 Essential Training (2018.03)\01 -
Traceback (most recent call last):
  File ".\lld.py", line 354, in <module>
    renameOldFolder(course_folder_path, chapter_index, extractedName, file_path)
  File ".\lld.py", line 236, in renameOldFolder
    os.rename(file, file_path)
WindowsError: [Error 183] Cannot create a file when that file already exists
PS C:\linkedin-learning-downloader-master\linkedin-learning-downloader-master>

DESCRIPTION OF COURSE:

Course details
7h 26m Beginner Released: March 22, 2018 20 chapter quizzes

**Comment by mclmza** [comment]
Code refactored and issue fixed.
