### ISSUE TITLE
Manual entry for courses

### ISSUE THREAD

**Issue by jAckercod3** [mclmza/linkedin-learning-downloader#71]
This is happening when config file has no courses and it is not adding courses from website unlike it's predecessor. ref fig1. and if i manuall add course this happens fig 2. and fig 2.1

<a href="https://imgur.com/kDQ2QMB"><img src="https://i.imgur.com/kDQ2QMB.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/gGCRSTV"><img src="https://i.imgur.com/gGCRSTV.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/Eg0i11q"><img src="https://i.imgur.com/Eg0i11q.png" title="source: imgur.com" /></a>

**Comment by mclmza** [comment]
The feature that fetch courses from bookmark was too buggy, so I decided to remove it for now.
The problem appears because the first chapter doesn't have a name, I'll commit a fix soon.

**Comment by jAckercod3** [comment]
Thank you for your response. is it possible to download particular video from course ? for e.g 
https://www.linkedin.com/learning/learning-autocad-lt/line-command-options , line-command -options video from course 'learning-autocad-lt'. ( this is just an example).

**Comment by mclmza** [comment]
For now this feature is not implemented, I'll think about implementing it.

**Comment by mclmza** [comment]
Pushed a commit that fixes your bug.
