### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SUBS'

### ISSUE THREAD

**Issue by jAckercod3** [mclmza/linkedin-learning-downloader#72]
this issue i faced from another course
<a href="https://imgur.com/tErs9Er"><img src="https://i.imgur.com/tErs9Er.png" title="source: imgur.com" /></a>

**Comment by MustafaWIthA** [comment]
you should comment out the two places of the subtitles ..... line 152-162 and 80-93

**Comment by jAckercod3** [comment]
@MustafaWIthA thank you for your response dear, but wish i could know how to do it. still a beginer and learning. really thank full if could help me out as my subscription will end on June 3, 2018.

**Comment by jAckercod3** [comment]
Thank you dear

**Comment by mclmza** [comment]
@jAckercod3 add SUBS = True to your config.py file.
