### ISSUE TITLE
Can't download excersice files

### ISSUE THREAD

**Issue by hyber-code** [mclmza/linkedin-learning-downloader#75]
At the end of course script prints can't down load excercise files

find below two examples

1
<a href="https://imgur.com/15Jf2Fs"><img src="https://i.imgur.com/15Jf2Fs.png" title="source: imgur.com" /></a>

2

<a href="https://imgur.com/1zJN6Cu"><img src="https://i.imgur.com/1zJN6Cu.png" title="source: imgur.com" /></a>

**Comment by kgoniszewski** [comment]
There is a mistake in index name : go to lld.py file and in lines 166 and167 change(delete) one letter:
"course_data['ex**c**erciseFiles']..." to "course_data['exerciseFiles']..."

**Comment by hyber-code** [comment]
Thank you dear

**Comment by kgoniszewski** [comment]
No problem. 

I found one more to change - there is an index error exception if there's no exercise file in the course. 
To handle this error you should change line No 168 in lld.py to:  except (KeyError,IndexError):

**Comment by kgoniszewski** [comment]
Ok, I think I managed to resolve above problem: in lld.py file method "download_courses" should look like this: (watch out for correct indentation!)

`    def download_courses(self):
        token = self.session.cookies.get('JSESSIONID').replace('"', '')
        self.session.headers['Csrf-Token'] = token
        self.session.headers['Cookie'] = self.plain_cookies(requests.utils.dict_from_cookiejar(self.session.cookies))
        self.session.headers.pop('Accept')

        for course in config.COURSES:
            resp = self.session.get(course_api_url % course)
            course_data = resp.json()['elements'][0]
            course_name = self.format_string(course_data['title'])
            logging.info('Starting download of course [%s]...' % course_name)
            course_path = '%s/%s' % (self.base_path, course_name)
            chapters_list = course_data['chapters']
            chapter_index = 1
            logging.info('Parsing course\'s chapters...')
            logging.info('%d chapters found' % len(chapters_list))
            for chapter in chapters_list:
                chapter_name = self.format_string(chapter['title'])
                logging.info('Starting download of chapter [%s]...' % chapter_name)
                chapter_path = '%s/%s - %s' % (course_path, str(chapter_index).zfill(2), chapter_name)
                if chapter_name == '':
                    chapter_path = chapter_path[:-3]
                videos_list = chapter['videos']
                video_index = 1
                logging.info('Parsing chapters\'s videos')
                logging.info('%d videos found' % len(videos_list))
                for video in videos_list:
                    video_name = self.format_string(video['title'])
                    video_slug = video['slug']
                    video_data = (self.session.get(video_api_url % (course, video_slug)))
                    try:
                        video_url = re.search('"progressiveUrl":"(.+)","streamingUrl"', video_data.text).group(1)
                    except:
                        logging.error('Can\'t download the video [%s], probably is only for premium users' % video_name)
                        continue
                    logging.info('Downloading video [%s]' % video_name)
                    self.download_file(video_url, chapter_path, '%s - %s.mp4' % (str(video_index).zfill(2), video_name))
                    video_data = video_data.json()['elements'][0]
                    if config.SUBS:
                        try:
                            subs = video_data['selectedVideo']['transcript']['lines']
                        except KeyError:
                            logging.info('No subtitles avaible')
                        else:
                            logging.info('Downloading subtitles')
                            self.download_sub(subs, chapter_path, '%s - %s.srt' % (str(video_index).zfill(2), video_name))
                    video_index += 1
                chapter_index += 1
            no_of_exercise_files = len(course_data['exerciseFiles'])
            for no in range(no_of_exercise_files):
                try:
                    ex_name = course_data['exerciseFiles'][no]['name']
                    ex_url = course_data['exerciseFiles'][no]['url']
                except (KeyError, IndexError):
                    logging.info('Can\'t download exercise files for course [%s]' % course_name)
                else:
                    self.download_file(ex_url, course_path, ex_name)
            description = course_data['description']
            logging.info('Downloading course description')
            self.download_desc(description, 'https://www.linkedin.com/learning/%s' % course, course_path, 'Description.txt')
`

**Comment by sojusnik** [comment]
Great! Would be great to update the initial script with your contribution.

kgoniszewski <notifications@github.com> schrieb am Sa., 9. Juni 2018 um
19:28 Uhr:

**Comment by hyber-code** [comment]
Really appreciate your efforts , so we just need to replace these lines

**Comment by mclmza** [comment]
Let me know if the scripts works now

**Comment by kgoniszewski** [comment]
Lines 165 - 174 (starting from "exercises_list = course_data['exerciseFiles']" ) : you should remove 4 spaces indentation (it's one level too deep and it causes that exercise files are downloaded multiple times)

**Comment by mclmza** [comment]
Mea culpa. Check it now.

**Comment by dipayan83** [comment]
getting below error while running in python 3.5
Traceback (most recent call last):
  File "D:\linkedin_learning\lld.py", line 187, in <module>
    main()
  File "D:\linkedin_learning\lld.py", line 183, in main
    lld.download_courses()
  File "D:\linkedin_learning\lld.py", line 125, in download_courses
    course_data = resp.json()['elements'][0]
KeyError: 'elements'

**Comment by basilbaby81** [comment]
Use Python 2

**Comment by ImranTufail02** [comment]
can anyone tell me how can I solve this error.  
![capture](https://user-images.githubusercontent.com/25123977/42996177-3a35eff8-8c2c-11e8-9c65-1b40532c9fd3.PNG)
