### ISSUE TITLE
keyerror: elements

### ISSUE THREAD

**Issue by mgg0d** [mclmza/linkedin-learning-downloader#78]
Hi, please tell me what is going on here, I have been dealing with it for the past 12 hours couldnt get it working:
C:\Users\meysa\Desktop\1>python lld.py
2018-06-14 11:50:23,625 - INFO - Authenticating to LinkedIn
2018-06-14 11:50:24,687 - INFO - Csfr token: e894a950-5891-4e82-8290-c04cdfa63461
2018-06-14 11:50:25,387 - INFO - Authentication successfully completed
Traceback (most recent call last):
  File "lld.py", line 187, in <module>
    main()
  File "lld.py", line 183, in main
    lld.download_courses()
  File "lld.py", line 125, in download_courses
    course_data = resp.json()['elements'][0]
KeyError: 'elements'

**Comment by inoutux** [comment]
Hi! I had the same error but I have upgrade python version and modules writting: sudo pip intall -r requirements. Then, write on console: python lld.py   and no error reports :)

**Comment by mgg0d** [comment]
@inoutux is it still working bro ? i cant get it working, what is your python version ?

**Comment by mgg0d** [comment]
hey guys, i fixed the issue, it had too many url parsing issues.

**Comment by mgg0d** [comment]
but still special thanks to the author, it has unbelievable integration

**Comment by sumit-anantwar** [comment]
I am getting the same error, how did you fix it?

**Comment by mclmza** [comment]
Thanks!

**Comment by sojusnik** [comment]
@mgg0d How exactly did you solve this problem?

**Comment by surajasawa** [comment]
key error elements 
this error is occurring continuously

**Comment by sumit-anantwar** [comment]
COURSES array, should contain only the course slug, not the URL.
Please post your config,py and I would be able to explain you better.

**Comment by surajasawa** [comment]
Sorted, thankyou

**Comment by hchugtai** [comment]
I have the same issue, can someone help me resolving this. I checked the name of course which are ok. Infact i did downloaded some but now facing this error.

**Comment by sumit-anantwar** [comment]
Post the **COURSES** array here. The problem will surely be in the names.
