### ISSUE TITLE
 reload(sys): NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by Elschnuppero** [mclmza/linkedin-learning-downloader#83]
Hi there,

installing the requirements.txt works fine. But when i execute python lld.py the following error comes up:

``Traceback (most recent call last):
  File "C:\Users\Seb\Desktop\py\lld.py", line 13, in <module>
    reload(sys)
NameError: name 'reload' is not defined``

Any idea? Thanks

**Comment by basilbaby81** [comment]
Use python 2

**Comment by Elschnuppero** [comment]
worked. thx.
