### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by armia142** [mclmza/linkedin-learning-downloader#89]
![000106-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/40745071/42139863-172d0720-7d96-11e8-828b-e94e49bea044.jpg)
![000107-config py - c__users_armia magdy_downloads_linkedin-learning-downloader-master_l](https://user-images.githubusercontent.com/40745071/42139864-17554c62-7d96-11e8-991d-9594181a8d13.jpg)

I'm new to python and I don't know where is the issue?

**Comment by basilbaby81** [comment]
Which version of python you are using .. use Python version 2 to run this
scripts.
 Go to python2 folder and use pim2 command instead of pim.

Hope you set the download base path in the config file

**Comment by armia142** [comment]
thanks brooo :D
